import Position from '../../classes/position';

export default class StructureTree {
    constructor() {
        this.id = 0;
        this.name = "";
        this.parentstructure = 0;
        this.featured = false;
        this.nameshortened = "";
        this.structuretype = 0;
        this.structureregion = 0;
        this.city = "";
        this.street = "";
        this.rank = 0;
        this.department = false;
        this.curator = 0;
        this.head = 0;
        this.changeorigin = 0;
        this.changestructurelast = 0;
        this.changestructurerename = false;
        this.changestructureall = false;
        this.changestructurerank = false;
        this.changestructurelocation = false;
        this.changestructureparent = false;
        this.priority = 0;
        this.printreward = false;
        this.main = false;
        this.name1 = "";
        this.name2 = "";
        this.name3 = "";
        this.name4 = "";
        this.name5 = "";
        this.name6 = "";
        this.separatestructure = false;
        this.subject1 = 0;
        this.subject2 = 0;
        this.subject3 = 0;
        this.subject4 = 0;
        this.subject5 = 0;
        this.subject6 = 0;
        this.subject7 = 0;
        this.subject8 = 0;
        this.subject9 = 0;
        this.subject10 = 0;
        this.subject11 = 0;
        this.subject12 = 0;
        this.subject13 = 0;
        this.subject14 = 0;
        this.subject15 = 0;
        this.subjectnumber = 0;
        this.subjectnotice = "";
        this.subjectgender = 0;
        this.subjectindex = 0;

        this.children_structures = [];
        this.actual_positions = [];
    };

    id: number;
    name: string;
    parentstructure: number;
    featured: boolean;
    nameshortened: string;
    structuretype: number;
    structureregion: number;
    city: string;
    street: string;
    rank: number;
    department: boolean;
    curator: number;
    head: number;
    changeorigin: number;
    changestructurelast: number;
    changestructurerename: boolean;
    changestructureall: boolean;
    changestructurerank: boolean;
    changestructurelocation: boolean;
    changestructureparent: boolean;
    priority: number;
    printreward: boolean;
    main: boolean;
    name1: string;
    name2: string;
    name3: string;
    name4: string;
    name5: string;
    name6: string;
    separatestructure: boolean;
    subject1: number;
    subject2: number;
    subject3: number;
    subject4: number;
    subject5: number;
    subject6: number;
    subject7: number;
    subject8: number;
    subject9: number;
    subject10: number;
    subject11: number;
    subject12: number;
    subject13: number;
    subject14: number;
    subject15: number;
    subjectnumber: number;
    subjectnotice: string;
    subjectgender: number;
    subjectindex: number;

    children_structures: StructureTree[];
    actual_positions: Position[];
}